apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | default "mycluster" }}-cluster-secret
  namespace: {{ .Release.Namespace }}
stringData:
  rootUser: {{ .Values.credentials.root.user | default "root" }}
  rootHost: {{ .Values.credentials.root.host | default "%%" | quote }}
  rootPassword: {{ .Values.credentials.root.password | default "sakila" }}
