apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: {{ .Release.Name | default "mycluster" }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ required "serverInstances is required" .Values.serverInstances }}
  router:
    instances: {{ required "routerInstances is required" .Values.routerInstances }}
  secretName: {{ .Release.Name }}-cluster-secret
  imagePullPolicy : {{ required "image.pullPolicy is required" .Values.image.pullPolicy }}
  baseServerId: {{ required "baseServerId is required" .Values.baseServerId }}
  version: {{ .Values.serverVersion | default .Chart.AppVersion }}
  serviceAccountName: {{ .Release.Name }}-sa

{{ if .Values.datadirVolumeClaimTemplate }}
{{ with .Values.datadirVolumeClaimTemplate }}
  datadirVolumeClaimTemplate:
{{ if .accessModes }}
    accessModes: [ "{{ .accessModes }}" ]
{{ end }}
    resources:
      requests:
{{- if .resources.requests.storage }}
        storage: "{{ .resources.requests.storage }}"
{{ end }}# if .resources.requests.storage
{{ end }}# with .Values.datadirVolumeClaimTemplate
{{ end }}# .Values.datadirVolumeClaimTemplate

{{ if and (and .Values.initDB.dump .Values.initDB.dump.name) (and .Values.initDB.clone .Values.initDB.donorUrl) }}
{{ fail "Dump and Clone are mutually exclusive" }}
{{ end }}# if and .dump .clone

{{ if and .Values.initDB .Values.initDB.clone }}
{{ with .Values.initDB.clone }}
  initDB:
    clone:
      donorUrl: {{ required "initDB.clone.donorUrl is required" .donorUrl }}
      rootUser: {{ .rootUser | default "root" }}
      credentials: {{ required "initDB.clone.credentials is required" .credentials }}
{{ end }}# with .Values.initDB.clone
{{ end }}# if and .Values.initDB .Values.initDB.clone

{{ if and .Values.initDB .Values.initDB.dump }}
{{ with .Values.initDB.dump }}
{{ if and .name (or .ociObjectStorage .persistentVolumeClaim) }}
  initDB:
    dump:
{{ if .name }}
      name: {{ .name }}
{{ end }}
{{ if .path }}
      path: {{ .path }}
{{ end }}
      storage:
{{ if .ociObjectStorage }}
        ociObjectStorage:
          prefix: {{ required "initDB.dump.ociObjectStorage.prefix is required" .ociObjectStorage.prefix }}
          bucketName: {{ required "initDB.dump.ociObjectStorage.bucketName is required" .ociObjectStorage.bucketName }}
          credentials: {{ required "initDB.dump.ociObjectStorage.credentials is required" .ociObjectStorage.credentials }} 
{{ end }}# .ociObjectStorage
{{ if .persistentVolumeClaim }}
        persistentVolumeClaim:
          {{- toYaml .persistentVolumeClaim | nindent 10}}
{{ end }}# .persistentVolumeClaim
{{ end }}# and .name (or .ociObjectStorage .persistentVolumeClaim)
{{ end }}# with .Values.initDB.dump
{{ end }}# and .Values.initDB .Values.initDB.dump

{{ if .Values.backupProfiles }}
  backupProfiles:
{{ end }}# .Values.backupProfiles