image:
  registry:
  repository: mysql
  name: mysql-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullSecrets:
    enabled: false
    secretName:
    registry:
    username:
    password:
    email:

credentials:
  root:
    user: root
    password: sakila
    host: "%"

#serverVersion: 8.0.26
serverInstances: 3
routerInstances: 3
baseServerId: 1000

#datadirVolumeClaimTemplate:
#  accessModes:
#  resources:
#    requests:
#      storage:

#initDB:
#  dump:
#    name:
#    path:
#    options:
#      includeSchemas:
#    ociObjectStorage:
#      prefix:
#      bucketName:
#      credentials:
#    persistentVolumeClaim:     
#  clone:
#    donorUrl:
#    rootUser:
#    credentials:

# Unused
#backupProfiles:
#- name: dump-instance-profile-pvc
#  dumpInstance:
#    dumpOptions:
#      excludeSchemas: ["excludeme"]
#    storage:
#      persistentVolumeClaim:
#        claimName: backup-volume-claim-1
#- name: dump-instance-profile-oci
#  dumpInstance:
#    dumpOptions:
#      excludeSchemas: ["excludeme"]
#    storage:
#      ociObjectStorage:
#        prefix : /
#        bucketName: idbcluster_backup
#        credentials: oci-credentials
#
#- name: snapshot-profile-oci
#  snapshot:
#    storage:
#      ociObjectStorage:
#        prefix : /
#        bucketName: idbcluster_backup
#        credentials: oci-credentials
# Unused
serviceAccount:
  annotations: {}

# Unused
podAnnotations: {}

# Unused
podSecurityContext: {}
  # fsGroup: 2000

# Unused
securityContext: {}

# Unused
resources: {}

# Unused
nodeSelector: {}

# Unused
tolerations: []

# Unused
affinity: {}
