apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-sa
  namespace: mysql-operator
{{- if .Values.image.pullSecrets.enabled }}
imagePullSecrets:
- name: {{ .Values.image.pullSecrets.secretName | default "priv-reg-secret" }}
{{- end }}